services:
  ipfs:
    container_name: ipfs-daemon
    image: ipfs/kubo:v0.27.0
    restart: unless-stopped
    volumes:
      - ./ipfs/data:/data/ipfs
      - ./ipfs/staging:/export
      - ./scripts/001-test.sh:/container-init.d/001-test.sh
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
    command: ["daemon", "--enable-gc", "--migrate=true", "--agent-version-suffix=docker"]

  libp2p:
    container_name: libp2p-proxy
    restart: unless-stopped
    build:
      context: ./libp2p-ws-proxy/.
    ports:
      - 127.0.0.1:8888:8888
      - 127.0.0.1:9999:9999